# Generated by Django 5.1.4 on 2024-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningquestion',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningquestion',
            name='key',
            field=models.JSONField(default=list),
        ),
    ]
